
window.FITLYNE_CONFIG = {
  API_URL: "rLcChgQXWk0B3Hdx9ri1MXEWnYavX2V3L9_fgFOXpJ4eCOUjRYYTNbg9ydmKCcOQ/exec",
  CLOUDINARY_CLOUD_NAME: "SEU_CLOUD_NAME",
  CLOUDINARY_UPLOAD_PRESET: "SEU_UNSIGNED_UPLOAD_PRESET",
  CLOUDINARY_WATERMARK_PUBLIC_ID: "fitlyne/logo",
  STORE_NAME: "FITLYNE",
  STORE_SUBTITLE: "Moda Fitness & Makeup"
};
