window.FITLYNE_CONFIG = {
  API_URL: "COLE_AQUI_A_URL_DO_APPS_SCRIPT_TERMINADA_EM_EXEC",
  CLOUDINARY_CLOUD_NAME: "SEU_CLOUD_NAME",
  CLOUDINARY_UPLOAD_PRESET: "SEU_UNSIGNED_UPLOAD_PRESET",
  CLOUDINARY_WATERMARK_PUBLIC_ID: "fitlyne/logo",
  STORE_NAME: "FITLYNE",
  STORE_SUBTITLE: "Moda Fitness & Makeup"
};
